//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCAngularHotelBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class apcust
    {
        public int apsqlno { get; set; }
        public string apcust_no { get; set; }
        public string apclass { get; set; }
        public string cust_area { get; set; }
        public Nullable<int> cust_seq { get; set; }
        public string ap_cname1 { get; set; }
        public string ap_cname2 { get; set; }
        public string ap_ename1 { get; set; }
        public string ap_ename2 { get; set; }
        public string ap_crep { get; set; }
        public string ap_erep { get; set; }
        public string ap_country { get; set; }
        public string ap_zip { get; set; }
        public string ap_addr1 { get; set; }
        public string ap_addr2 { get; set; }
        public string ap_eaddr1 { get; set; }
        public string ap_eaddr2 { get; set; }
        public string ap_eaddr3 { get; set; }
        public string ap_eaddr4 { get; set; }
        public string apatt_zip { get; set; }
        public string apatt_addr1 { get; set; }
        public string apatt_addr2 { get; set; }
        public string apatt_tel0 { get; set; }
        public string apatt_tel { get; set; }
        public string apatt_tel1 { get; set; }
        public string apatt_fax { get; set; }
        public Nullable<System.DateTime> in_date { get; set; }
        public string ap_code { get; set; }
        public Nullable<System.DateTime> tran_date { get; set; }
        public string tran_scode { get; set; }
        public string dmp_seq { get; set; }
        public string exp_seq { get; set; }
        public string dmt_seq { get; set; }
        public string ext_seq { get; set; }
        public string mark { get; set; }
        public string ap_title { get; set; }
        public string ap_fcname { get; set; }
        public string ap_lcname { get; set; }
        public string ap_fename { get; set; }
        public string ap_lename { get; set; }
        public string apatt_email { get; set; }
    }
}
