//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCAngularHotelBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class country
    {
        public string coun_code { get; set; }
        public string coun_e { get; set; }
        public string coun_c { get; set; }
        public string cl { get; set; }
        public string ccode { get; set; }
        public string markc { get; set; }
        public string buss_c { get; set; }
        public Nullable<System.DateTime> tran_date { get; set; }
        public string tran_scode { get; set; }
        public string markb { get; set; }
        public string markf { get; set; }
    }
}
