//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCAngularHotelBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class custz
    {
        public string cust_area { get; set; }
        public int cust_seq { get; set; }
        public string id_no { get; set; }
        public string www { get; set; }
        public string email { get; set; }
        public string con_code { get; set; }
        public Nullable<System.DateTime> con_term { get; set; }
        public string acc_zip { get; set; }
        public string acc_addr1 { get; set; }
        public string acc_addr2 { get; set; }
        public string acc_tel0 { get; set; }
        public string acc_tel { get; set; }
        public string acc_tel1 { get; set; }
        public string acc_fax { get; set; }
        public string rmark_code { get; set; }
        public Nullable<int> ref_seq { get; set; }
        public string ref_no { get; set; }
        public string mag { get; set; }
        public string pscode { get; set; }
        public string plevel { get; set; }
        public string pdis_type { get; set; }
        public string ppay_type { get; set; }
        public string tscode { get; set; }
        public string tlevel { get; set; }
        public string tdis_type { get; set; }
        public string tpay_type { get; set; }
        public Nullable<System.DateTime> dmt_date { get; set; }
        public Nullable<System.DateTime> ext_date { get; set; }
        public Nullable<System.DateTime> dmp_date { get; set; }
        public Nullable<System.DateTime> exp_date { get; set; }
        public Nullable<System.DateTime> in_date { get; set; }
        public string in_scode { get; set; }
        public string tran_code { get; set; }
        public Nullable<System.DateTime> ttran_date { get; set; }
        public string ttran_scode { get; set; }
        public Nullable<System.DateTime> ptran_date { get; set; }
        public string ptran_scode { get; set; }
        public string cust_remark { get; set; }
        public string mark { get; set; }
        public string tran_remark { get; set; }
        public string tran_ctrl { get; set; }
        public Nullable<System.DateTime> tran_output { get; set; }
        public Nullable<System.DateTime> tran_upmail { get; set; }
        public string pacc_email { get; set; }
        public string tacc_email { get; set; }
        public string tacc_zip { get; set; }
        public string tacc_addr1 { get; set; }
        public string tacc_addr2 { get; set; }
        public string tacc_tel0 { get; set; }
        public string tacc_tel { get; set; }
        public string tacc_tel1 { get; set; }
        public string tacc_fax { get; set; }
        public string acc_remark { get; set; }
        public string pspay_flag { get; set; }
        public Nullable<short> pspay_mm { get; set; }
        public string tspay_flag { get; set; }
        public Nullable<short> tspay_mm { get; set; }
        public string pacc_chkcode { get; set; }
        public string tacc_chkcode { get; set; }
        public string pacc_attention { get; set; }
        public string pacc_title { get; set; }
        public string tacc_attention { get; set; }
        public string tacc_title { get; set; }
        public string tax_zip { get; set; }
        public string tax_addr1 { get; set; }
        public string tax_addr2 { get; set; }
        public string tax_tel0 { get; set; }
        public string tax_tel { get; set; }
        public string tax_tel1 { get; set; }
        public string tax_fax { get; set; }
        public string payout_mark { get; set; }
        public Nullable<int> tpay_typem { get; set; }
        public Nullable<int> ppay_typem { get; set; }
        public string pspay_source { get; set; }
        public string pspay_seq { get; set; }
        public string pspay_refno { get; set; }
        public string tspay_source { get; set; }
        public string tspay_seq { get; set; }
        public string tspay_refno { get; set; }
        public string tax_attention { get; set; }
        public string tax_email { get; set; }
        public string taxacc_attention { get; set; }
        public string taxacc_email { get; set; }
        public string taxacc_zip { get; set; }
        public string taxacc_addr1 { get; set; }
        public string taxacc_addr2 { get; set; }
        public string taxacc_tel0 { get; set; }
        public string taxacc_tel { get; set; }
        public string taxacc_tel1 { get; set; }
        public string taxacc_fax { get; set; }
    }
}
