//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCAngularHotelBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cust_code
    {
        public string Code_type { get; set; }
        public string Cust_code1 { get; set; }
        public string Code_name { get; set; }
        public Nullable<int> Sql { get; set; }
        public string SortFld { get; set; }
        public string form_name { get; set; }
        public string Ref_code { get; set; }
        public string Dept { get; set; }
        public string Remark { get; set; }
        public string Mark { get; set; }
        public string mark1 { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<System.DateTime> tran_date { get; set; }
    }
}
