//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCAngularHotelBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class custz_att
    {
        public string cust_area { get; set; }
        public int cust_seq { get; set; }
        public short att_sql { get; set; }
        public string dept { get; set; }
        public string attention { get; set; }
        public string att_company { get; set; }
        public string att_title { get; set; }
        public string att_dept { get; set; }
        public string att_tel0 { get; set; }
        public string att_tel { get; set; }
        public string att_tel1 { get; set; }
        public string att_mobile { get; set; }
        public string att_fax { get; set; }
        public string att_zip { get; set; }
        public string att_addr1 { get; set; }
        public string att_addr2 { get; set; }
        public string att_email { get; set; }
        public string att_mag { get; set; }
        public string att_code { get; set; }
        public Nullable<System.DateTime> ttran_date { get; set; }
        public string ttran_scode { get; set; }
        public Nullable<System.DateTime> ptran_date { get; set; }
        public string ptran_scode { get; set; }
        public string mark { get; set; }
    }
}
