//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCAngularHotelBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomBooking
    {
        public int BookingID { get; set; }
        public Nullable<int> RoomID { get; set; }
        public string BookedDateFR { get; set; }
        public string BookedDateTO { get; set; }
        public string BookingStatus { get; set; }
        public string PaymentStatus { get; set; }
        public string AdvancePayed { get; set; }
        public string TotalAmountPayed { get; set; }
    }
}
