//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCAngularHotelBooking
{
    using System;
    using System.Collections.Generic;
    
    public partial class scode
    {
        public string scode1 { get; set; }
        public string sys_pwd { get; set; }
        public string sc_name { get; set; }
        public string se_name { get; set; }
        public string UserType { get; set; }
        public string lev { get; set; }
        public string Email { get; set; }
        public string sscode { get; set; }
        public Nullable<System.DateTime> beg_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<System.DateTime> LastVisit { get; set; }
        public Nullable<int> VisitCount { get; set; }
        public string ReMark { get; set; }
        public string comp { get; set; }
        public string mark1 { get; set; }
        public string mark2 { get; set; }
        public Nullable<System.DateTime> tran_date { get; set; }
        public string tran_scode { get; set; }
    }
}
